spring:
  application:
    name: bookmate
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ${MAIL_PASSWORD}
  jpa:
    database: mysql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
jwt:
  secret-key: ${JWT_SECRET}
  access-token: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION}

aladin:
  api-key: ${ALADIN_API_KEY}

openai:
  model: ${OPENAI_MODEL}
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_URL}

springdoc:
  api-docs:
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    # try it out 기능에 요청이 수행되는 소요시간을 표시
    display-request-duration: true
    # 문서를 로드할때 기본적으로 API가 모두 접힌 상태로 설정
    # list: 태그만 펼침, full: 모든 API 펼침
    doc-expansion: none